### ISSUE TITLE
Too large segment duration

### ISSUE THREAD

**Issue by Erk-** [sile/hls_m3u8#1]
At the moment it panics if the segment duration is larger than the target duration, but apples [media stream validator] only erros if the segment duration is 2 seconds more than the target duration. This may not be an issue but the lib fails with some of apples test streams because of this.

[media stream validator]: https://developer.apple.com/library/archive/technotes/tn2235/_index.html#//apple_ref/doc/uid/DTS40010221-CH1-VALIDATORTOOL

**Comment by sile** [comment]
The RFC of HLS (RFC 8216) says,

> The EXTINF duration of each Media Segment in the Playlist
>  file, when rounded to the nearest integer, MUST be less than or equal
>   to the target duration.

Thus, I think current implementation is correct as the default behaviour.
But, in practice, some HLS servers may generate not so good m3u8 file (e.g., it contains a segment duration exceeds the target duration). To rescue such case, [`MediaPlaylistOptions`] was added at the commit https://github.com/sile/hls_m3u8/commit/ab82edf11921ea7c183068ed0fc0b1145183a7fd.
By using the struct, the reported problem can be solved as follows:
```rust
use hls_m3u8::MediaPlaylist;
use std::time::Duration;

let m3u8 = "#EXTM3U
#EXT-X-TARGETDURATION:5
#EXT-X-VERSION:3
#EXTINF:7
http://media.example.com/first.ts
#EXT-X-ENDLIST";

// The default behaviour.
assert!(m3u8.parse::<MediaPlaylist>().is_err());  // Error

// Allows the above segment
let result =
    MediaPlaylistOptions::new()
        .allowable_excess_segment_duration(Duration::from_secs(2))
        .parse(m3u8);
assert!(result.is_ok()); // OK
```

[`MediaPlaylistOptions`]: https://docs.rs/hls_m3u8/0.1.2/hls_m3u8/struct.MediaPlaylistOptions.html

**Comment by Erk-** [comment]
Thanks this fixes my problem.
