### ISSUE TITLE
Hardening of the lib

### ISSUE THREAD

**Issue by Erk-** [sile/hls_m3u8#10]
I did a small amount of fuzzing and found that it is pretty easy to provoke a panic when parsing master playlists. I would say that it would be better if it reported an error like `Malformed input` instead of failing with `Never fails`. I have attached a file with tests for some panics.
[fuzz_tests.rs](https://gist.github.com/Erk-/683159df6ef3641cecc2fcb6a78895de)

**Comment by sile** [comment]
Thank you for reporting this issue.
I would like to improve error handlings of this library.
I'm too busy this month, so I'll deal with this in the next month.
