### ISSUE TITLE
Add Apache 2.0 license

### ISSUE THREAD

**Issue by Luro02** [sile/hls_m3u8#15]
It seems to be recommended to add the Apache 2.0 license additionally to the MIT. This is obviously no requirement, but why not? It'd be a shame, if some developer couldn't use this library, because it isn't licensed under Apache 2.0.

https://rust-lang-nursery.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive

**Comment by sile** [comment]
Sounds good.
There is no reason to refuse to include the Apache 2.0 license in `hls_m3u8`.
