### ISSUE TITLE
Panics with "Never fails" if you parse an empty string as a media playlist

### ISSUE THREAD

**Issue by Erk-** [sile/hls_m3u8#2]
Example:
```rust
    #[test]
    fn empty_hls_parse() {
        let m3u8 = "";

        assert!(m3u8.parse::<MediaPlaylist>().is_err()); // Panics with 'Never fails'
    }
```
The panic seems to come from here: https://github.com/sile/hls_m3u8/blob/master/src/media_playlist.rs#L178

**Comment by sile** [comment]
Thank you for reporting this bug.
I fixed it at the commit https://github.com/sile/hls_m3u8/commit/3122949384d1d42856e4f648444f6713def4bd36.
