### ISSUE TITLE
How do I mutate an existing MediaSegment?

### ISSUE THREAD

**Issue by whmountains** [sile/hls_m3u8#4]
The fields are private and there are no methods to mutate it.  I also don't see any straightforward way to convert MediaSegment to MediaSegmentBuilder.

**Comment by sile** [comment]
As you say, there is no easy way to mutate an existing `MediaSegment`.

For converting `MediaSegment` to `MediaSegmentBuilder`, you need to write code as follows:
```rust
let segment: MediaSegment = ...; 

let mut builder = MediaSegmentBuilder::new();

builder.uri(segment.uri().clone());
builder.tag(segment.inf_tag().clone());
if let Some(t) = segment.byte_range_tag() {
    builder.tag(t);
}
if let Some(t) = segment.date_range_tag().cloned() {
    builder.tag(t);
}
if let Some(t) = segment.discontinuity_tag() {
    builder.tag(t);
}
if let Some(t) = segment.program_date_time_tag().cloned() {
    builder.tag(t);
}
if let Some(t) = segment.map_tag().cloned() {
    builder.tag(t);
}
for t in segment.key_tags() {
    builder.tag(t.clone());
}

builder.finish();
```

If you want the functionality, I think that it's OK to add setter methods (or mutable accessors like `inf_tag_mut()`) to `MediaSegment`.
