### ISSUE TITLE
Ready for 0.3?

### ISSUE THREAD

**Issue by daltonclaybrook** [sile/hls_m3u8#42]
Is it time to release another version with the latest changes? Personally, I need the setters [added to stream_inf.rs in this commit](https://github.com/sile/hls_m3u8/commit/81f9a421fe9d0dd2e6f56c2d676d18b8aec53022#diff-941eaa4eac7f8abbe0911ec72c488bbb). I would be happy to help/contribute if something is blocking this release.

**Comment by Luro02** [comment]
this would have to be v.0.3, because some of the changes are breaking changes. The only thing, that is blocking a new release is missing documentation and the 2 open prs. I will look into resolving them later today...

**Comment by Luro02** [comment]
Another thing, that I would like to change is the error type. (thiserror seems like a nice solution).

(I will take care of it this weekend)

**Comment by Luro02** [comment]
You can look at this milestone to see the progress and what issues remain. https://github.com/sile/hls_m3u8/milestone/1

**Comment by Luro02** [comment]
@sile a new version can be published :)

**Comment by sile** [comment]
@Luro02 Thank a lot for your great efforts!
Published the new version: https://crates.io/crates/hls_m3u8/0.3.0
