### ISSUE TITLE
hls_m3u8 panics on m3u8 version 6 playlist

### ISSUE THREAD

**Issue by Candunc** [sile/hls_m3u8#55]
I've run into an issue with hls_m3u8 crate version 0.3.0 failing to parse a playlist and I suspect it is due to the library being unable to parse the audio lines - removal of them causes the panic to change from:

 ```Error { inner: Builder { message: "invalid input" } }``` to 

```Error { inner: Builder { message: "unmatched group: \"audio_aac_1\"" } }```

I've attached the broken playlist.

[broken_playlist.txt](https://github.com/sile/hls_m3u8/files/4530433/broken_playlist.txt)

**Comment by Luro02** [comment]
Thanks for making an issue :)
