### ISSUE TITLE
Missing value for BANDWIDTH

### ISSUE THREAD

**Issue by chengyuhui** [sile/hls_m3u8#64]
I got the following m3u8 from a CDN server:
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=10000000
https://995107575.cloudvdn.com/a.m3u8?cdn=cn-gotcha03&domain=d1--cn-gotcha103.bilivideo.com&expires=1614619920&len=0&oi=1891753406&order=1&player=70YAALwcl0b9RGgW&pt=h5&ptype=0&qn=10000&secondToken=secondToken%3ACZ4ggpPHomuwcnT8XWDjJUp9eh8&sign=325afc8bc3b01ccbadeac084004ece64&sigparams=cdn%2Cexpires%2Clen%2Coi%2Cpt%2Cqn%2Ctrid&sl=1&src=4&streamid=live-qn%3Alive-qn%2Flive_402401719_42665292&trid=20d9f245179b4ef3a7e3635afaaa87ea&v3=1
```
Parsing this gives me a
```
 [src\main.rs:14] MasterPlaylist::try_from(s) = Err(
    Error {
        inner: MissingValue {
            value: "BANDWIDTH",
        },
    },
)
```
with the following code
```rust
let s = "#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=10000000
https://995107575.cloudvdn.com/a.m3u8?cdn=cn-gotcha03&domain=d1--cn-gotcha103.bilivideo.com&expires=1614619920&len=0&oi=1891753406&order=1&player=70YAALwcl0b9RGgW&pt=h5&ptype=0&qn=10000&secondToken=secondToken%3ACZ4ggpPHomuwcnT8XWDjJUp9eh8&sign=325afc8bc3b01ccbadeac084004ece64&sigparams=cdn%2Cexpires%2Clen%2Coi%2Cpt%2Cqn%2Ctrid&sl=1&src=4&streamid=live-qn%3Alive-qn%2Flive_402401719_42665292&trid=20d9f245179b4ef3a7e3635afaaa87ea&v3=1";
dbg!(MasterPlaylist::try_from(s));
```
This can not be a formatting issue as feeding the parser with the exact response string yields the same result. Am I doing something wrong?

**Comment by Luro02** [comment]
Hey, I am currently quite busy with university exams, so it might take a while until I fix this issue (eta. would be end of march).

You know that there is a space between the `PROGRAM-ID=1, BANDWIDTH=10000000`. From where did you obtain this m3u8 file? Did you create it yourself or was it made by someone else?

Either way to fix this, you have to make the following changes:

```diff
            self.index = end + 1;

-            &self.string[start..end]
+            // remove trailing and leading whitespace from the key
+            (&self.string[start..end]).trim()
```
([`src/attribute.rs#L33`](https://github.com/sile/hls_m3u8/blob/23c799a88bd70c8e0a4f358882f5a9bbaba7ba40/src/attribute.rs#L33))
and
```diff
            };

            self.index += end;
            self.index -= start;

-            &self.string[start..end]
+            // remove trailing and leading whitespace from the value
+            (&self.string[start..end]).trim()
        };
```
([`src/attribute.rs#L69`](https://github.com/sile/hls_m3u8/blob/23c799a88bd70c8e0a4f358882f5a9bbaba7ba40/src/attribute.rs#L69))

Feel free to create a PR for this issue, if you do not want to wait for me to fix it. It would also be nice to have tests in the attribute.rs file for both changes (so this issue does not happen again).

I hope you have a nice day :)

**Comment by Luro02** [comment]
To quote the RFC:
> Certain tags have values that are attribute-lists.  An attribute-list
   is a comma-separated list of attribute/value pairs with no
   whitespace.


https://tools.ietf.org/html/rfc8216#section-4.2

#27

**Comment by chengyuhui** [comment]
Oh... didn't know that that file is malformed, as I got it from a CDN of a video distribution service. Both `hls.js` and the Node.js library I'm using in other projects seem to handle this fine.

Will look into PR this when I have time.
