### ISSUE TITLE
Add integration tests in a "tests" folder

### ISSUE THREAD

**Issue by Luro02** [sile/hls_m3u8#8]
Some projects like [hyper](https://github.com/hyperium/hyper/tree/master/tests) or [serde](https://github.com/serde-rs/serde/tree/master/test_suite/tests) have their tests in a separate folder called `tests`. This makes it easier (at least for me) to read the source code and tests.
## For example
``` rust
#[cfg(test)]
mod tests  {
    #[test]
    fn it_works() {
        assert_eq!(true, true);
    }
}
```
will become
``` rust
#[test]
fn it_works() {
    assert_eq!(true, true);
}
```

**Comment by sile** [comment]
Thank you for your suggestion.

By reading [Test Organization](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests) section of *The Rust Programming Language*, separate `tests` directory seems suited to write integration tests rather than unit tests.

> In Rust, integration tests are entirely external to your library. They use your library in the same way any other code would, which means they can only call functions that are part of your library’s public API. Their purpose is to test whether many parts of your library work together correctly. Units of code that work correctly on their own could have problems when integrated, so test coverage of the integrated code is important as well. To create integration tests, you first need a *tests* directory.

**Comment by Luro02** [comment]
Thanks for the information, I didn't know about this :)
I thought the `tests` folder was simply a better way to have your tests organized.

**Comment by Luro02** [comment]
### Useful resources;
https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming
https://github.com/video-dev/hls.js/tree/master/tests
https://github.com/globocom/m3u8/tree/master/tests
https://github.com/grafov/m3u8/tree/master/sample-playlists
https://github.com/quangngotan95/go-m3u8/tree/master/test/fixtures
