### ISSUE TITLE
Convert wrapper types to their "true" types

### ISSUE THREAD

**Issue by Luro02** [sile/hls_m3u8#9]
A lot of types in this library only add complexity and could be replaced with better types. For example a `QuotedString`; most of the time you don't want quotation marks at the start + end of the string, so you have to remove them by hand:
``` rust
let unquoted = quoted.to_string().replace("\"", "");
```
or parsing a `SingleLineString` to an [Url](https://docs.rs/url/2.1.0/url/struct.Url.html):
``` rust
let url = Url::parse(&segment.uri().to_string())?;
```
`MediaSegment::key_tags()`
``` rust
let keys = vec![];
for key in segment.key_tags() {
    keys.push(key.key().unwrap().clone());
}
```
It'd be a lot more helpful, if the library directly returns the type, that it's supposed to be instead of a `QuotedString` or `SingleLineString`.
Here is a table of what could be replaced:

Old | New
-- | --
| `HexadecimalSequence` | `Vec<u8>`/`&[u8]` |
| `DecimalResolution` | `(usize, usize)` |
| `QuotedString` | `String::new().replace("\"", "")` |
| `SingleLineString` | `String` |
|`&[ExtXKey(DecryptionKey)]` | `&[ExtXKey]` |

**Comment by sile** [comment]
> It'd be a lot more helpful, if the library directly returns the type

That makes sense.
I think this conversion is a good idea.
